package mediamtx

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ConfigOptions are the values the generated MediaMTX configuration needs.
type ConfigOptions struct {
	RTMPAddress string
	APIAddress  string
	IngestPath  string

	// RemoteIngest, when non-nil, is Stage 20D2C's explicit
	// --remote-ingest opt-in (docs/remote-ingest.md §3/§4/§5). Nil is
	// the default for every other deployment mode (desktop, plain
	// --headless, --headless --remote-management without ingest) and
	// produces byte-identical output to every prior stage - see
	// TestRenderConfigGolden.
	RemoteIngest *RemoteIngestOptions
}

// RemoteIngestOptions configures the additional RTMPS listener and
// MediaMTX-native authentication Stage 20D2C adds (docs/remote-
// ingest.md §4/§5). RTMPAddress/APIAddress above are never changed by
// this - they stay the existing loopback-only listeners, unconditionally
// validated loopback by config.loadMediaMTX exactly as before
// (docs/remote-ingest.md §4's "optional" resolution): branch FFmpeg and
// the Go backend's own Control API polling keep using them completely
// unaffected by remote ingest being enabled.
type RemoteIngestOptions struct {
	// RTMPSAddress is the new, non-loopback-capable RTMPS listener a
	// remote OBS instance publishes to. Never equal to RTMPAddress or
	// APIAddress (config.loadRemoteIngest enforces this).
	RTMPSAddress string

	// ServerKeyPath / ServerCertPath are the operator-supplied TLS
	// private key and certificate paths (docs/remote-ingest.md §8),
	// delivered via systemd LoadCredential= and read once at startup -
	// never a value this application generates or stores itself.
	ServerKeyPath  string
	ServerCertPath string

	// PublisherUser is the fixed, non-secret remote-publisher service
	// identity (docs/remote-ingest.md §5), e.g. "streaming-tree-obs".
	// Not a secret; only PublisherPassVerifier is.
	PublisherUser string

	// PublisherPassVerifier is already the MediaMTX-native "sha256:
	// <base64(sha256(secret))>" verifier (docs/remote-ingest.md §6) -
	// never the plaintext secret. Empty means no remote-publisher
	// credential is provisioned yet; RemoteIngest may still be non-nil
	// in that state (the RTMPS listener and the local-only read/api
	// identity are configured, but nothing can successfully publish
	// until a credential is provisioned).
	PublisherPassVerifier string
}

// ConfigFileName is the generated configuration inside the runtime directory.
const ConfigFileName = "mediamtx.yml"

// ConfigPath is where the generated configuration is written.
//
// It lives in the runtime directory beside the managed installation, never in
// the repository: it is generated output, not something a user edits.
func ConfigPath(dataDir string) string {
	return filepath.Join(RuntimeDir(dataDir), ConfigFileName)
}

// RenderConfig produces the MediaMTX v1.19.3 configuration.
//
// Every key below exists in the v1.19.3 reference configuration. MediaMTX
// rejects an unknown key outright and refuses to start, so this function is
// pinned to one schema and is covered by a golden test.
//
// Services are disabled explicitly rather than left to upstream defaults: RTSP,
// HLS, WebRTC, SRT and MoQ all listen on their own ports by default, and this
// application only ever needs RTMP in and a loopback Control API.
//
// The output is deterministic - no timestamps, no map iteration - so the golden
// test is meaningful and a rewrite produces an identical file.
func RenderConfig(opts ConfigOptions) string {
	var b strings.Builder

	b.WriteString("# Generated by Streaming Tree for OBS. Do not edit.\n")
	b.WriteString("# Regenerated on every backend start; manual changes are lost.\n")
	b.WriteString("# Target: MediaMTX " + SupportedVersion + "\n")
	b.WriteString("\n")

	b.WriteString("# Logging goes to stdout so the supervisor can capture it.\n")
	b.WriteString("logLevel: info\n")
	b.WriteString("logDestinations: [stdout]\n")
	b.WriteString("logStructured: true\n")
	b.WriteString("\n")

	b.WriteString("readTimeout: 10s\n")
	b.WriteString("writeTimeout: 10s\n")
	b.WriteString("\n")

	b.WriteString("# Control API: loopback only, read by the Go backend alone.\n")
	b.WriteString("# The browser never talks to it.\n")
	b.WriteString("api: true\n")
	b.WriteString("apiAddress: " + opts.APIAddress + "\n")
	b.WriteString("\n")

	if opts.RemoteIngest == nil {
		b.WriteString("# RTMP ingest: the only public-facing listener, loopback only.\n")
		b.WriteString("rtmp: true\n")
		b.WriteString("rtmpAddress: " + opts.RTMPAddress + "\n")
		b.WriteString("rtmpEncryption: \"no\"\n")
		b.WriteString("\n")
	} else {
		ri := opts.RemoteIngest
		b.WriteString("# RTMP ingest: rtmpAddress stays loopback-only (branch FFmpeg's\n")
		b.WriteString("# own input, unauthenticated within this application's own trust\n")
		b.WriteString("# boundary); rtmpsAddress is the new Stage 20D2C remote-ingest\n")
		b.WriteString("# listener a remote OBS instance publishes to over RTMPS. \"optional\"\n")
		b.WriteString("# opens both simultaneously - see docs/remote-ingest.md §4 for why\n")
		b.WriteString("# \"strict\" (RTMPS-only, one listener) was rejected: it would have\n")
		b.WriteString("# forced branch FFmpeg's own loopback read onto RTMPS too.\n")
		b.WriteString("rtmp: true\n")
		b.WriteString("rtmpAddress: " + opts.RTMPAddress + "\n")
		b.WriteString("rtmpEncryption: \"optional\"\n")
		b.WriteString("rtmpsAddress: " + ri.RTMPSAddress + "\n")
		b.WriteString("rtmpServerKey: " + ri.ServerKeyPath + "\n")
		b.WriteString("rtmpServerCert: " + ri.ServerCertPath + "\n")
		b.WriteString("\n")

		b.WriteString("# Stage 20D2C: MediaMTX-native authentication. The remote publisher\n")
		b.WriteString("# identity may only publish, to exactly the canonical path. The\n")
		b.WriteString("# local identity is restricted to loopback callers (branch FFmpeg's\n")
		b.WriteString("# own read, the Go backend's own Control API polling) and never\n")
		b.WriteString("# needs a password - the loopback IP restriction is the boundary.\n")
		b.WriteString("# A request matching neither entry is refused by MediaMTX itself.\n")
		b.WriteString("authMethod: internal\n")
		b.WriteString("authInternalUsers:\n")
		b.WriteString("  - user: " + ri.PublisherUser + "\n")
		b.WriteString("    pass: " + ri.PublisherPassVerifier + "\n")
		b.WriteString("    ips: []\n")
		b.WriteString("    permissions:\n")
		b.WriteString("      - action: publish\n")
		b.WriteString("        path: " + opts.IngestPath + "\n")
		b.WriteString("  - user: any\n")
		b.WriteString("    ips: [127.0.0.1, ::1]\n")
		b.WriteString("    permissions:\n")
		b.WriteString("      - action: read\n")
		b.WriteString("        path: " + opts.IngestPath + "\n")
		b.WriteString("      - action: api\n")
		b.WriteString("\n")
	}

	b.WriteString("# Everything unused is disabled explicitly rather than left\n")
	b.WriteString("# to upstream defaults, which would open extra listeners.\n")
	b.WriteString("rtsp: false\n")
	b.WriteString("hls: false\n")
	b.WriteString("webrtc: false\n")
	b.WriteString("srt: false\n")
	b.WriteString("moq: false\n")
	b.WriteString("metrics: false\n")
	b.WriteString("pprof: false\n")
	b.WriteString("playback: false\n")
	b.WriteString("\n")

	b.WriteString("pathDefaults:\n")
	b.WriteString("  # No recording and no forwarding: this stage receives only.\n")
	b.WriteString("  record: false\n")
	b.WriteString("\n")

	b.WriteString("paths:\n")
	b.WriteString("  # Exactly one path accepts publishing. There is no wildcard\n")
	b.WriteString("  # entry, so any other path is refused.\n")
	b.WriteString("  " + opts.IngestPath + ":\n")
	b.WriteString("    source: publisher\n")
	b.WriteString("    # A second publisher must not silently displace the first.\n")
	b.WriteString("    overridePublisher: false\n")

	return b.String()
}

// WriteConfig renders and atomically writes the configuration.
//
// The file is written to a temporary name and renamed into place, so MediaMTX
// can never read a half-written configuration, and it is created with
// restrictive permissions where the platform supports them.
func WriteConfig(dataDir string, opts ConfigOptions) (string, error) {
	target := ConfigPath(dataDir)

	if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
		return "", fmt.Errorf("create the runtime directory: %w", err)
	}

	temp, err := os.CreateTemp(filepath.Dir(target), ".mediamtx-*.yml")
	if err != nil {
		return "", fmt.Errorf("create the temporary configuration: %w", err)
	}
	tempName := temp.Name()
	defer func() {
		// No-op once the rename succeeded.
		_ = os.Remove(tempName)
	}()

	if _, err := temp.WriteString(RenderConfig(opts)); err != nil {
		_ = temp.Close()
		return "", fmt.Errorf("write the configuration: %w", err)
	}
	if err := temp.Chmod(0o600); err != nil && !isChmodUnsupported(err) {
		_ = temp.Close()
		return "", fmt.Errorf("set configuration permissions: %w", err)
	}
	if err := temp.Close(); err != nil {
		return "", fmt.Errorf("close the configuration: %w", err)
	}

	if err := os.Rename(tempName, target); err != nil {
		return "", fmt.Errorf("publish the configuration: %w", err)
	}

	return target, nil
}

// isChmodUnsupported reports whether chmod is meaningless on this platform.
func isChmodUnsupported(err error) bool {
	// Windows has no POSIX mode bits; Go emulates chmod only for the read-only
	// attribute, and some filesystems reject it outright.
	return os.IsPermission(err) || strings.Contains(err.Error(), "not supported")
}
