package mediamtx

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func renderDefault() string {
	return RenderConfig(ConfigOptions{
		RTMPAddress: "127.0.0.1:1935",
		APIAddress:  "127.0.0.1:9997",
		IngestPath:  "live",
	})
}

func TestRenderConfigIsDeterministic(t *testing.T) {
	first := renderDefault()
	for i := 0; i < 5; i++ {
		if renderDefault() != first {
			t.Fatal("RenderConfig() produced different output for identical input")
		}
	}
}

// TestRenderConfigGolden pins the exact generated file.
//
// The value is inlined rather than kept in a separate fixture so a reviewer
// sees precisely what MediaMTX will be given. Every key below was verified
// against the real v1.19.3 reference configuration; MediaMTX rejects an unknown
// key and refuses to start, so this test guards against a typo shipping.
func TestRenderConfigGolden(t *testing.T) {
	want := `# Generated by Streaming Tree for OBS. Do not edit.
# Regenerated on every backend start; manual changes are lost.
# Target: MediaMTX v1.19.3

# Logging goes to stdout so the supervisor can capture it.
logLevel: info
logDestinations: [stdout]
logStructured: true

readTimeout: 10s
writeTimeout: 10s

# Control API: loopback only, read by the Go backend alone.
# The browser never talks to it.
api: true
apiAddress: 127.0.0.1:9997

# RTMP ingest: the only public-facing listener, loopback only.
rtmp: true
rtmpAddress: 127.0.0.1:1935
rtmpEncryption: "no"

# Everything unused is disabled explicitly rather than left
# to upstream defaults, which would open extra listeners.
rtsp: false
hls: false
webrtc: false
srt: false
moq: false
metrics: false
pprof: false
playback: false

pathDefaults:
  # No recording and no forwarding: this stage receives only.
  record: false

paths:
  # Exactly one path accepts publishing. There is no wildcard
  # entry, so any other path is refused.
  live:
    source: publisher
    # A second publisher must not silently displace the first.
    overridePublisher: false
`

	if got := renderDefault(); got != want {
		t.Errorf("generated configuration changed.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRenderConfigBindsBothListenersToLoopback(t *testing.T) {
	config := renderDefault()

	if !strings.Contains(config, "rtmpAddress: 127.0.0.1:1935") {
		t.Error("the RTMP listener is not bound to loopback")
	}
	if !strings.Contains(config, "apiAddress: 127.0.0.1:9997") {
		t.Error("the Control API listener is not bound to loopback")
	}
	// Nothing may bind to every interface. A bare ":1935" (no host) is checked
	// per line, because "127.0.0.1:1935" legitimately ends with ":1935".
	for _, forbidden := range []string{"0.0.0.0", "[::]"} {
		if strings.Contains(config, forbidden) {
			t.Errorf("the configuration contains the wildcard bind %q", forbidden)
		}
	}
	for _, line := range strings.Split(config, "\n") {
		trimmed := strings.TrimSpace(line)
		for _, key := range []string{"rtmpAddress:", "apiAddress:"} {
			if after, found := strings.CutPrefix(trimmed, key); found {
				address := strings.TrimSpace(after)
				if strings.HasPrefix(address, ":") {
					t.Errorf("%s binds every interface (%q)", key, address)
				}
			}
		}
	}
}

func TestRenderConfigDisablesUnusedServices(t *testing.T) {
	config := renderDefault()

	// Each of these opens its own listener by default, so leaving any to the
	// upstream default would expose a service this application never uses.
	for _, service := range []string{"rtsp", "hls", "webrtc", "srt", "moq", "metrics", "pprof", "playback"} {
		if !strings.Contains(config, service+": false") {
			t.Errorf("%s is not explicitly disabled", service)
		}
	}
}

func TestRenderConfigEnablesOnlyRTMPAndTheAPI(t *testing.T) {
	config := renderDefault()

	if !strings.Contains(config, "rtmp: true") {
		t.Error("RTMP is not enabled")
	}
	if !strings.Contains(config, "api: true") {
		t.Error("the Control API is not enabled")
	}
}

func TestRenderConfigDefinesOnlyTheConfiguredPath(t *testing.T) {
	config := RenderConfig(ConfigOptions{
		RTMPAddress: "127.0.0.1:1935",
		APIAddress:  "127.0.0.1:9997",
		IngestPath:  "obs_input",
	})

	if !strings.Contains(config, "  obs_input:\n") {
		t.Error("the configured ingest path is missing")
	}
	// A wildcard entry would let a publisher use any path it liked.
	for _, wildcard := range []string{"  all:", "  all_others:", "  \"~", "  '~"} {
		if strings.Contains(config, wildcard) {
			t.Errorf("the configuration contains the wildcard path %q", wildcard)
		}
	}
}

func TestRenderConfigUsesAPublisherSourceAndForbidsTakeover(t *testing.T) {
	config := renderDefault()

	if !strings.Contains(config, "source: publisher") {
		t.Error("the path source is not 'publisher'")
	}
	// MediaMTX defaults overridePublisher to true, which would let a second
	// publisher silently displace the first.
	if !strings.Contains(config, "overridePublisher: false") {
		t.Error("a second publisher may still displace the first")
	}
}

func TestRenderConfigDisablesRecordingAndCarriesNoDestinations(t *testing.T) {
	config := renderDefault()

	if !strings.Contains(config, "record: false") {
		t.Error("recording is not disabled")
	}

	// No destination platform, credential or forwarding rule may appear.
	lower := strings.ToLower(config)
	for _, forbidden := range []string{
		"twitch", "youtube", "kick", "tiktok",
		"streamkey", "stream_key", "password", "token", "secret",
		"runonready", "runonpublish", "runondemand",
	} {
		if strings.Contains(lower, forbidden) {
			t.Errorf("the configuration contains %q, which it must never carry", forbidden)
		}
	}
}

func TestWriteConfigIsAtomicAndLeavesNoTemporaryFile(t *testing.T) {
	dataDir := t.TempDir()

	path, err := WriteConfig(dataDir, ConfigOptions{
		RTMPAddress: "127.0.0.1:1935",
		APIAddress:  "127.0.0.1:9997",
		IngestPath:  "live",
	})
	if err != nil {
		t.Fatalf("WriteConfig() returned an error: %v", err)
	}

	if path != ConfigPath(dataDir) {
		t.Errorf("path = %q, want %q", path, ConfigPath(dataDir))
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read the written configuration: %v", err)
	}
	if string(content) != renderDefault() {
		t.Error("the written configuration differs from the rendered one")
	}

	// The temporary file used for the atomic rename must be gone.
	entries, err := os.ReadDir(filepath.Dir(path))
	if err != nil {
		t.Fatalf("read the runtime directory: %v", err)
	}
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), ".mediamtx-") {
			t.Errorf("a temporary file was left behind: %s", entry.Name())
		}
	}
}

func TestWriteConfigOverwritesAnExistingFile(t *testing.T) {
	dataDir := t.TempDir()
	opts := ConfigOptions{RTMPAddress: "127.0.0.1:1935", APIAddress: "127.0.0.1:9997", IngestPath: "live"}

	if _, err := WriteConfig(dataDir, opts); err != nil {
		t.Fatalf("first WriteConfig() returned an error: %v", err)
	}

	opts.IngestPath = "second"
	path, err := WriteConfig(dataDir, opts)
	if err != nil {
		t.Fatalf("second WriteConfig() returned an error: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read the configuration: %v", err)
	}
	if !strings.Contains(string(content), "  second:") {
		t.Error("the configuration was not regenerated")
	}
}

// renderRemoteIngest renders a configuration with Stage 20D2C remote
// ingest enabled - a fixed, representative RemoteIngestOptions used by
// every test below, mirroring renderDefault()'s own role for the
// non-ingest path.
func renderRemoteIngest() string {
	return RenderConfig(ConfigOptions{
		RTMPAddress: "127.0.0.1:1935",
		APIAddress:  "127.0.0.1:9997",
		IngestPath:  "live",
		RemoteIngest: &RemoteIngestOptions{
			RTMPSAddress:          "0.0.0.0:1936",
			ServerKeyPath:         "/run/credentials/streaming-tree.service/streaming-tree-rtmps-key",
			ServerCertPath:        "/run/credentials/streaming-tree.service/streaming-tree-rtmps-cert",
			PublisherUser:         "streaming-tree-obs",
			PublisherPassVerifier: "sha256:BdSWkrdV+ZxFBLUQQY7+7uv9RmiSVA8nrPmjGjJtZQQ=",
		},
	})
}

func TestRenderConfigNilRemoteIngestIsByteIdenticalToNoField(t *testing.T) {
	// A ConfigOptions with RemoteIngest explicitly nil (the zero value)
	// must render exactly like renderDefault() - every non-D2C
	// deployment mode leaves this field unset.
	got := RenderConfig(ConfigOptions{
		RTMPAddress:  "127.0.0.1:1935",
		APIAddress:   "127.0.0.1:9997",
		IngestPath:   "live",
		RemoteIngest: nil,
	})
	if got != renderDefault() {
		t.Error("a nil RemoteIngest changed the generated configuration")
	}
}

func TestRenderConfigRemoteIngestKeepsRTMPAddressLoopback(t *testing.T) {
	config := renderRemoteIngest()

	if !strings.Contains(config, "rtmpAddress: 127.0.0.1:1935") {
		t.Error("rtmpAddress changed when remote ingest was enabled - branch FFmpeg's own loopback read must be unaffected")
	}
	if !strings.Contains(config, "rtmpsAddress: 0.0.0.0:1936") {
		t.Error("rtmpsAddress is missing or wrong")
	}
	if !strings.Contains(config, "rtmpEncryption: \"optional\"") {
		t.Error(`rtmpEncryption must be "optional" when remote ingest is enabled (docs/remote-ingest.md §4)`)
	}
	if strings.Contains(config, `rtmpEncryption: "no"`) {
		t.Error("the plaintext-only rtmpEncryption value leaked into the remote-ingest configuration")
	}
	if strings.Contains(config, `rtmpEncryption: "strict"`) {
		t.Error(`"strict" mode was explicitly rejected (docs/remote-ingest.md §4) - it would break branch FFmpeg's own loopback read`)
	}
}

func TestRenderConfigRemoteIngestNeverContainsThePlaintextSecret(t *testing.T) {
	// The verifier passed in is already "sha256:<base64>" - RenderConfig
	// must never see or emit the plaintext secret itself. This test
	// stands in for that guarantee by asserting the rendered output
	// contains only the sha256: form and nothing resembling a second,
	// unprefixed secret value.
	config := renderRemoteIngest()

	if !strings.Contains(config, "pass: sha256:BdSWkrdV+ZxFBLUQQY7+7uv9RmiSVA8nrPmjGjJtZQQ=") {
		t.Error("the sha256: verifier is missing from the rendered configuration")
	}
	if strings.Count(config, "pass:") != 1 {
		t.Errorf("expected exactly one pass: line, found %d", strings.Count(config, "pass:"))
	}
}

func TestRenderConfigRemoteIngestGrantsPublishOnlyToTheRemoteIdentity(t *testing.T) {
	config := renderRemoteIngest()

	if !strings.Contains(config, "user: streaming-tree-obs") {
		t.Error("the remote publisher identity is missing")
	}
	if !strings.Contains(config, "ips: []") {
		t.Error("the remote publisher identity must allow any source IP (ips: [])")
	}

	// The remote-publisher block must grant exactly one permission
	// (publish, to the canonical path) - verified by isolating the text
	// between "user: streaming-tree-obs" and the next "  - user:".
	start := strings.Index(config, "user: streaming-tree-obs")
	rest := config[start:]
	next := strings.Index(rest[1:], "  - user:")
	block := rest
	if next >= 0 {
		block = rest[:next+1]
	}
	if !strings.Contains(block, "action: publish") {
		t.Error("the remote publisher identity is missing its publish permission")
	}
	if strings.Contains(block, "action: read") || strings.Contains(block, "action: api") || strings.Contains(block, "action: playback") {
		t.Error("the remote publisher identity must never be granted read/api/playback")
	}
	if !strings.Contains(block, "path: live") {
		t.Error("the remote publisher's publish permission is not scoped to the canonical path")
	}
}

func TestRenderConfigRemoteIngestRestrictsTheLocalIdentityToLoopback(t *testing.T) {
	config := renderRemoteIngest()

	if !strings.Contains(config, "user: any") {
		t.Error("the local internal identity (user: any) is missing")
	}
	if !strings.Contains(config, "ips: [127.0.0.1, ::1]") {
		t.Error("the local internal identity must be restricted to loopback IPs")
	}

	start := strings.Index(config, "user: any")
	block := config[start:]
	if !strings.Contains(block, "action: read") {
		t.Error("the local internal identity is missing its read permission")
	}
	if !strings.Contains(block, "action: api") {
		t.Error("the local internal identity is missing its api permission")
	}
	if strings.Contains(block, "action: publish") {
		t.Error("the local internal identity must never be granted publish - only the remote credential may publish")
	}
}

func TestRenderConfigRemoteIngestNeverBindsRTMPSToLoopbackOnly(t *testing.T) {
	// This is a sanity check on the test fixture, not a runtime
	// enforcement: config.loadRemoteIngest (apps/server/internal/config)
	// is what actually rejects a loopback rtmpsAddress at startup. This
	// guards against a future refactor accidentally making
	// RenderConfig itself silently rewrite the address.
	config := renderRemoteIngest()
	if !strings.Contains(config, "rtmpsAddress: 0.0.0.0:1936") {
		t.Error("rtmpsAddress was not rendered as given")
	}
}

func TestConfigPathLivesInTheRuntimeDirectory(t *testing.T) {
	path := ConfigPath("/data")

	// Generated output belongs beside the managed installation, never in the
	// repository and never where a user would expect to edit it.
	if !strings.Contains(filepath.ToSlash(path), "/runtime/") {
		t.Errorf("config path = %q, want it under the runtime directory", path)
	}
}
