package mediamtx

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func renderDefault() string {
	return RenderConfig(ConfigOptions{
		RTMPAddress: "127.0.0.1:1935",
		APIAddress:  "127.0.0.1:9997",
		IngestPath:  "live",
	})
}

func TestRenderConfigIsDeterministic(t *testing.T) {
	first := renderDefault()
	for i := 0; i < 5; i++ {
		if renderDefault() != first {
			t.Fatal("RenderConfig() produced different output for identical input")
		}
	}
}

// TestRenderConfigGolden pins the exact generated file.
//
// The value is inlined rather than kept in a separate fixture so a reviewer
// sees precisely what MediaMTX will be given. Every key below was verified
// against the real v1.19.3 reference configuration; MediaMTX rejects an unknown
// key and refuses to start, so this test guards against a typo shipping.
func TestRenderConfigGolden(t *testing.T) {
	want := `# Generated by Streaming Tree for OBS. Do not edit.
# Regenerated on every backend start; manual changes are lost.
# Target: MediaMTX v1.19.3

# Logging goes to stdout so the supervisor can capture it.
logLevel: info
logDestinations: [stdout]
logStructured: true

readTimeout: 10s
writeTimeout: 10s

# Control API: loopback only, read by the Go backend alone.
# The browser never talks to it.
api: true
apiAddress: 127.0.0.1:9997

# RTMP ingest: the only public-facing listener, loopback only.
rtmp: true
rtmpAddress: 127.0.0.1:1935
rtmpEncryption: "no"

# Everything unused is disabled explicitly rather than left
# to upstream defaults, which would open extra listeners.
rtsp: false
hls: false
webrtc: false
srt: false
moq: false
metrics: false
pprof: false
playback: false

pathDefaults:
  # No recording and no forwarding: this stage receives only.
  record: false

paths:
  # Exactly one path accepts publishing. There is no wildcard
  # entry, so any other path is refused.
  live:
    source: publisher
    # A second publisher must not silently displace the first.
    overridePublisher: false
`

	if got := renderDefault(); got != want {
		t.Errorf("generated configuration changed.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestRenderConfigBindsBothListenersToLoopback(t *testing.T) {
	config := renderDefault()

	if !strings.Contains(config, "rtmpAddress: 127.0.0.1:1935") {
		t.Error("the RTMP listener is not bound to loopback")
	}
	if !strings.Contains(config, "apiAddress: 127.0.0.1:9997") {
		t.Error("the Control API listener is not bound to loopback")
	}
	// Nothing may bind to every interface. A bare ":1935" (no host) is checked
	// per line, because "127.0.0.1:1935" legitimately ends with ":1935".
	for _, forbidden := range []string{"0.0.0.0", "[::]"} {
		if strings.Contains(config, forbidden) {
			t.Errorf("the configuration contains the wildcard bind %q", forbidden)
		}
	}
	for _, line := range strings.Split(config, "\n") {
		trimmed := strings.TrimSpace(line)
		for _, key := range []string{"rtmpAddress:", "apiAddress:"} {
			if after, found := strings.CutPrefix(trimmed, key); found {
				address := strings.TrimSpace(after)
				if strings.HasPrefix(address, ":") {
					t.Errorf("%s binds every interface (%q)", key, address)
				}
			}
		}
	}
}

func TestRenderConfigDisablesUnusedServices(t *testing.T) {
	config := renderDefault()

	// Each of these opens its own listener by default, so leaving any to the
	// upstream default would expose a service this application never uses.
	for _, service := range []string{"rtsp", "hls", "webrtc", "srt", "moq", "metrics", "pprof", "playback"} {
		if !strings.Contains(config, service+": false") {
			t.Errorf("%s is not explicitly disabled", service)
		}
	}
}

func TestRenderConfigEnablesOnlyRTMPAndTheAPI(t *testing.T) {
	config := renderDefault()

	if !strings.Contains(config, "rtmp: true") {
		t.Error("RTMP is not enabled")
	}
	if !strings.Contains(config, "api: true") {
		t.Error("the Control API is not enabled")
	}
}

func TestRenderConfigDefinesOnlyTheConfiguredPath(t *testing.T) {
	config := RenderConfig(ConfigOptions{
		RTMPAddress: "127.0.0.1:1935",
		APIAddress:  "127.0.0.1:9997",
		IngestPath:  "obs_input",
	})

	if !strings.Contains(config, "  obs_input:\n") {
		t.Error("the configured ingest path is missing")
	}
	// A wildcard entry would let a publisher use any path it liked.
	for _, wildcard := range []string{"  all:", "  all_others:", "  \"~", "  '~"} {
		if strings.Contains(config, wildcard) {
			t.Errorf("the configuration contains the wildcard path %q", wildcard)
		}
	}
}

func TestRenderConfigUsesAPublisherSourceAndForbidsTakeover(t *testing.T) {
	config := renderDefault()

	if !strings.Contains(config, "source: publisher") {
		t.Error("the path source is not 'publisher'")
	}
	// MediaMTX defaults overridePublisher to true, which would let a second
	// publisher silently displace the first.
	if !strings.Contains(config, "overridePublisher: false") {
		t.Error("a second publisher may still displace the first")
	}
}

func TestRenderConfigDisablesRecordingAndCarriesNoDestinations(t *testing.T) {
	config := renderDefault()

	if !strings.Contains(config, "record: false") {
		t.Error("recording is not disabled")
	}

	// No destination platform, credential or forwarding rule may appear.
	lower := strings.ToLower(config)
	for _, forbidden := range []string{
		"twitch", "youtube", "kick", "tiktok",
		"streamkey", "stream_key", "password", "token", "secret",
		"runonready", "runonpublish", "runondemand",
	} {
		if strings.Contains(lower, forbidden) {
			t.Errorf("the configuration contains %q, which it must never carry", forbidden)
		}
	}
}

func TestWriteConfigIsAtomicAndLeavesNoTemporaryFile(t *testing.T) {
	dataDir := t.TempDir()

	path, err := WriteConfig(dataDir, ConfigOptions{
		RTMPAddress: "127.0.0.1:1935",
		APIAddress:  "127.0.0.1:9997",
		IngestPath:  "live",
	})
	if err != nil {
		t.Fatalf("WriteConfig() returned an error: %v", err)
	}

	if path != ConfigPath(dataDir) {
		t.Errorf("path = %q, want %q", path, ConfigPath(dataDir))
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read the written configuration: %v", err)
	}
	if string(content) != renderDefault() {
		t.Error("the written configuration differs from the rendered one")
	}

	// The temporary file used for the atomic rename must be gone.
	entries, err := os.ReadDir(filepath.Dir(path))
	if err != nil {
		t.Fatalf("read the runtime directory: %v", err)
	}
	for _, entry := range entries {
		if strings.HasPrefix(entry.Name(), ".mediamtx-") {
			t.Errorf("a temporary file was left behind: %s", entry.Name())
		}
	}
}

func TestWriteConfigOverwritesAnExistingFile(t *testing.T) {
	dataDir := t.TempDir()
	opts := ConfigOptions{RTMPAddress: "127.0.0.1:1935", APIAddress: "127.0.0.1:9997", IngestPath: "live"}

	if _, err := WriteConfig(dataDir, opts); err != nil {
		t.Fatalf("first WriteConfig() returned an error: %v", err)
	}

	opts.IngestPath = "second"
	path, err := WriteConfig(dataDir, opts)
	if err != nil {
		t.Fatalf("second WriteConfig() returned an error: %v", err)
	}

	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read the configuration: %v", err)
	}
	if !strings.Contains(string(content), "  second:") {
		t.Error("the configuration was not regenerated")
	}
}

func TestConfigPathLivesInTheRuntimeDirectory(t *testing.T) {
	path := ConfigPath("/data")

	// Generated output belongs beside the managed installation, never in the
	// repository and never where a user would expect to edit it.
	if !strings.Contains(filepath.ToSlash(path), "/runtime/") {
		t.Errorf("config path = %q, want it under the runtime directory", path)
	}
}
