package mediamtx

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ConfigOptions are the values the generated MediaMTX configuration needs.
type ConfigOptions struct {
	RTMPAddress string
	APIAddress  string
	IngestPath  string
}

// ConfigFileName is the generated configuration inside the runtime directory.
const ConfigFileName = "mediamtx.yml"

// ConfigPath is where the generated configuration is written.
//
// It lives in the runtime directory beside the managed installation, never in
// the repository: it is generated output, not something a user edits.
func ConfigPath(dataDir string) string {
	return filepath.Join(RuntimeDir(dataDir), ConfigFileName)
}

// RenderConfig produces the MediaMTX v1.19.3 configuration.
//
// Every key below exists in the v1.19.3 reference configuration. MediaMTX
// rejects an unknown key outright and refuses to start, so this function is
// pinned to one schema and is covered by a golden test.
//
// Services are disabled explicitly rather than left to upstream defaults: RTSP,
// HLS, WebRTC, SRT and MoQ all listen on their own ports by default, and this
// application only ever needs RTMP in and a loopback Control API.
//
// The output is deterministic - no timestamps, no map iteration - so the golden
// test is meaningful and a rewrite produces an identical file.
func RenderConfig(opts ConfigOptions) string {
	var b strings.Builder

	b.WriteString("# Generated by Streaming Tree for OBS. Do not edit.\n")
	b.WriteString("# Regenerated on every backend start; manual changes are lost.\n")
	b.WriteString("# Target: MediaMTX " + SupportedVersion + "\n")
	b.WriteString("\n")

	b.WriteString("# Logging goes to stdout so the supervisor can capture it.\n")
	b.WriteString("logLevel: info\n")
	b.WriteString("logDestinations: [stdout]\n")
	b.WriteString("logStructured: true\n")
	b.WriteString("\n")

	b.WriteString("readTimeout: 10s\n")
	b.WriteString("writeTimeout: 10s\n")
	b.WriteString("\n")

	b.WriteString("# Control API: loopback only, read by the Go backend alone.\n")
	b.WriteString("# The browser never talks to it.\n")
	b.WriteString("api: true\n")
	b.WriteString("apiAddress: " + opts.APIAddress + "\n")
	b.WriteString("\n")

	b.WriteString("# RTMP ingest: the only public-facing listener, loopback only.\n")
	b.WriteString("rtmp: true\n")
	b.WriteString("rtmpAddress: " + opts.RTMPAddress + "\n")
	b.WriteString("rtmpEncryption: \"no\"\n")
	b.WriteString("\n")

	b.WriteString("# Everything unused is disabled explicitly rather than left\n")
	b.WriteString("# to upstream defaults, which would open extra listeners.\n")
	b.WriteString("rtsp: false\n")
	b.WriteString("hls: false\n")
	b.WriteString("webrtc: false\n")
	b.WriteString("srt: false\n")
	b.WriteString("moq: false\n")
	b.WriteString("metrics: false\n")
	b.WriteString("pprof: false\n")
	b.WriteString("playback: false\n")
	b.WriteString("\n")

	b.WriteString("pathDefaults:\n")
	b.WriteString("  # No recording and no forwarding: this stage receives only.\n")
	b.WriteString("  record: false\n")
	b.WriteString("\n")

	b.WriteString("paths:\n")
	b.WriteString("  # Exactly one path accepts publishing. There is no wildcard\n")
	b.WriteString("  # entry, so any other path is refused.\n")
	b.WriteString("  " + opts.IngestPath + ":\n")
	b.WriteString("    source: publisher\n")
	b.WriteString("    # A second publisher must not silently displace the first.\n")
	b.WriteString("    overridePublisher: false\n")

	return b.String()
}

// WriteConfig renders and atomically writes the configuration.
//
// The file is written to a temporary name and renamed into place, so MediaMTX
// can never read a half-written configuration, and it is created with
// restrictive permissions where the platform supports them.
func WriteConfig(dataDir string, opts ConfigOptions) (string, error) {
	target := ConfigPath(dataDir)

	if err := os.MkdirAll(filepath.Dir(target), 0o700); err != nil {
		return "", fmt.Errorf("create the runtime directory: %w", err)
	}

	temp, err := os.CreateTemp(filepath.Dir(target), ".mediamtx-*.yml")
	if err != nil {
		return "", fmt.Errorf("create the temporary configuration: %w", err)
	}
	tempName := temp.Name()
	defer func() {
		// No-op once the rename succeeded.
		_ = os.Remove(tempName)
	}()

	if _, err := temp.WriteString(RenderConfig(opts)); err != nil {
		_ = temp.Close()
		return "", fmt.Errorf("write the configuration: %w", err)
	}
	if err := temp.Chmod(0o600); err != nil && !isChmodUnsupported(err) {
		_ = temp.Close()
		return "", fmt.Errorf("set configuration permissions: %w", err)
	}
	if err := temp.Close(); err != nil {
		return "", fmt.Errorf("close the configuration: %w", err)
	}

	if err := os.Rename(tempName, target); err != nil {
		return "", fmt.Errorf("publish the configuration: %w", err)
	}

	return target, nil
}

// isChmodUnsupported reports whether chmod is meaningless on this platform.
func isChmodUnsupported(err error) bool {
	// Windows has no POSIX mode bits; Go emulates chmod only for the read-only
	// attribute, and some filesystems reject it outright.
	return os.IsPermission(err) || strings.Contains(err.Error(), "not supported")
}
