package engagement

import "time"

// Event is one provider-independent, normalized occurrence: a chat message,
// a follow, a subscription, and so on. See docs/engagement-architecture.md
// §5.2 for the design rationale behind each field.
//
// Deliberately excludes, and must never carry: any OAuth token, any raw
// provider payload, any WebSocket session id, any subscription id, any
// reconnect URL, any request header. A connector authenticates itself; it
// does not put credentials in the data it publishes here.
type Event struct {
	SchemaVersion SchemaVersion

	// Sequence and ReceivedAt are assigned by the Event Bus at publish time,
	// never by a connector - see internal/engagement.Bus.Publish. A
	// connector always leaves both at their zero value.
	Sequence   uint64
	ReceivedAt time.Time

	// ID is a globally unique internal identifier, generated by the bus at
	// publish time (see internal/engagement.Bus.Publish) - never invented by
	// a connector and never the same as ProviderEventID.
	ID string

	// ProviderEventID is the original ID the provider assigned, when it has
	// one. Empty for provider event types with no stable ID.
	ProviderEventID string
	ProviderID      ProviderID
	// ConnectedAccountID is the internal account (internal/domain/account)
	// that received this event.
	ConnectedAccountID string
	// DestinationID is the configured destination (internal/domain/platform)
	// this maps to, when unambiguously linked - empty when the connected
	// account is not linked to any destination.
	DestinationID string

	Type              Type
	ProviderEventType string
	PlatformTimestamp time.Time
	// Synthetic marks a preview/test event that never came from a real
	// connector. No Stage 8A code path sets this to true - it exists so the
	// model is ready for the preview/test events
	// docs/engagement-architecture.md §11 describes, without requiring a
	// second, parallel event type later.
	Synthetic bool

	// DedupeKey is a stable key a connector computes deterministically from
	// provider-stable identifiers (for the Twitch connector, the EventSub
	// delivery's metadata.message_id - see
	// docs/provider-integrations/twitch-engagement.md). The bus drops a
	// second event with a DedupeKey it has already seen within a bounded
	// recent window.
	DedupeKey string

	User    *User
	Message *Message

	// Money is set only for an event that genuinely carries a real
	// provider-reported monetary/paid-support amount (Stage 15A: YouTube
	// Super Chat/Super Sticker) - see money.go. Deliberately never a plain
	// float; nil for every event type that has no such amount.
	Money    *Money
	Quantity *int64

	// ModerationRef references the ID (or ProviderEventID) of the event
	// being moderated, for TypeChatMessageDeleted and TypeModeration.
	ModerationRef string
	// ModerationAction is a stable action identifier for TypeModeration
	// events that are not a simple message deletion (for example,
	// "clear_user_messages" - see
	// docs/provider-integrations/twitch-engagement.md).
	ModerationAction string

	// ProviderExtra is a small, explicitly-namespaced bag for fields a
	// connector wants to carry forward without promoting them to first-class
	// model fields. Deliberately not a raw JSON passthrough - see
	// validation.go's size/key limits. Generic consumers must not read it.
	ProviderExtra map[string]string
}
