//go:build ignore

// Generates every derived Windows/web icon asset from the one real,
// user-provided branding source (Stage 20E branding remediation).
//
// Canonical source: assets/branding/streaming-tree-logo.png - the real
// logo, provided directly by the operator (never invented/redrawn).
// Everything else in this file is a mechanical derivative of that one
// file: crop, downsample, repackage. There is deliberately no second
// copy of the artwork anywhere else in the repository - every consumer
// (tray, the .exe's own icon resource, the installer, Start Menu
// shortcuts, the web favicon) reads one of the files this script
// writes, and every one of those files traces back to the same source.
//
// The source is a square lockup: an emblem (a stylised circuit/tree
// mark with a play-button glyph) above the "STREAMING TREE for OBS"
// wordmark, on a transparent background (confirmed - true alpha, not a
// baked-in dark background: this project's own PNG preview tooling
// renders transparency as a dark gradient, which is a viewer artifact,
// not the file's real content, verified by sampling actual corner
// pixel alpha values directly before writing this script).
//
// Icon surfaces (tray/exe/taskbar/Start Menu, all real 16x16-scale
// contexts) use only the emblem, cropped out of the source - the full
// wordmark lockup is illegible at 16x16 and would not read as an icon,
// only as a smear. The crop rectangle below was measured directly
// against this exact source image (its emblem's own real alpha-channel
// bounding box, with the wordmark's own bounding box confirmed
// separate and excluded) - not estimated, not a fixed fraction of the
// canvas. If the source logo is ever replaced, this rectangle must be
// re-measured for the new file.
//
// Run with: go run scripts/generate-branding-assets.go
package main

import (
	"bytes"
	"encoding/binary"
	"image"
	"image/color"
	"image/png"
	_ "image/png"
	"log"
	"os"
)

const sourcePath = "assets/branding/streaming-tree-logo.png"

// emblemCrop is the emblem's own bounding box inside the 1024x1024
// source, measured by sampling the real alpha channel: the wordmark
// text begins widening sharply at y=650, so the crop's bottom edge
// stops there; the box is squared by extending upward (to y=39) rather
// than downward, so no wordmark pixel is ever included.
var emblemCrop = image.Rect(195, 39, 806, 650)

// iconSizes is the standard Windows icon size set this project embeds
// into every .ico it produces - covers the tray (16, matching
// tray_windows.go's own selectClosestFrame request), Explorer/Start
// Menu at every common DPI scale, and a large 256 frame for
// high-resolution contexts.
var iconSizes = []int{16, 24, 32, 48, 64, 128, 256}

func main() {
	src := loadImage(sourcePath)

	sb := src.Bounds()
	cropper, ok := src.(interface{ SubImage(image.Rectangle) image.Image })
	if !ok {
		log.Fatalf("%s does not support cropping (unexpected decoder type)", sourcePath)
	}
	crop := emblemCrop.Intersect(sb)
	emblem := cropper.SubImage(crop)

	var frames []*image.RGBA
	for _, size := range iconSizes {
		frames = append(frames, areaResize(emblem, size, size))
	}

	writeICOMustSucceed("apps/server/internal/runtime/tray/assets/tray.ico", frames)
	writeICOMustSucceed("apps/web/public/favicon.ico", frames)

	// The exe's own icon resource (embedded via a checked-in .syso -
	// see apps/server/cmd/server/README-icon.txt) is generated by the
	// separate go-winres tool, pointed at the same tray.ico this script
	// just wrote - not duplicated here, so there is exactly one
	// generated .ico file feeding both consumers.
	log.Println("wrote apps/server/internal/runtime/tray/assets/tray.ico")
	log.Println("wrote apps/web/public/favicon.ico")
	log.Println("next: regenerate the exe icon resource - see apps/server/cmd/server/README-icon.txt")
}

func loadImage(path string) image.Image {
	f, err := os.Open(path) // #nosec G304 -- fixed, repo-relative, developer-invoked script.
	if err != nil {
		log.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()
	img, _, err := image.Decode(f)
	if err != nil {
		log.Fatalf("decode %s: %v", path, err)
	}
	return img
}

// areaResize downsamples src to exactly w x h using area averaging
// (box filtering) - the right choice for the large minification ratios
// here (611px emblem down to as small as 16px): every source pixel in
// each destination pixel's footprint contributes, rather than only the
// few pixels a point-sampled or bilinear filter would touch, which
// avoids the aliasing/moire a cruder resize would produce on this
// source's fine circuit-line detail.
//
// color.Color.RGBA() returns alpha-premultiplied values by Go's own
// documented contract, so averaging its output directly (rather than
// un-premultiplied 8-bit RGB) is the mathematically correct way to
// blend colors across a transparency edge - a naive average of
// non-premultiplied values would leak dark fringes from fully
// transparent (black, alpha=0) neighboring pixels into semi-transparent
// edge pixels, exactly the artifact this avoids.
func areaResize(src image.Image, w, h int) *image.RGBA {
	sb := src.Bounds()
	sw, sh := sb.Dx(), sb.Dy()
	dst := image.NewRGBA(image.Rect(0, 0, w, h))

	for dy := 0; dy < h; dy++ {
		sy0 := dy * sh / h
		sy1 := (dy + 1) * sh / h
		if sy1 <= sy0 {
			sy1 = sy0 + 1
		}
		for dx := 0; dx < w; dx++ {
			sx0 := dx * sw / w
			sx1 := (dx + 1) * sw / w
			if sx1 <= sx0 {
				sx1 = sx0 + 1
			}

			var rSum, gSum, bSum, aSum, n uint64
			for sy := sy0; sy < sy1 && sy < sh; sy++ {
				for sx := sx0; sx < sx1 && sx < sw; sx++ {
					r, g, b, a := src.At(sb.Min.X+sx, sb.Min.Y+sy).RGBA()
					rSum += uint64(r)
					gSum += uint64(g)
					bSum += uint64(b)
					aSum += uint64(a)
					n++
				}
			}
			if n == 0 {
				n = 1
			}
			dst.SetRGBA(dx, dy, color.RGBA{
				R: uint8((rSum / n) >> 8),
				G: uint8((gSum / n) >> 8),
				B: uint8((bSum / n) >> 8),
				A: uint8((aSum / n) >> 8),
			})
		}
	}
	return dst
}

// writeICOMustSucceed wraps images (smallest to largest, in the order
// given) as a standard multi-frame Windows .ico - PNG-compressed
// frames, the format Windows has supported since Vista, exactly like
// the single-frame version this project's earlier tray-only icon used.
func writeICOMustSucceed(path string, images []*image.RGBA) {
	var buf bytes.Buffer

	type frame struct {
		png  []byte
		w, h int
	}
	frames := make([]frame, len(images))
	for i, img := range images {
		var pngBuf bytes.Buffer
		if err := png.Encode(&pngBuf, img); err != nil {
			log.Fatalf("encode frame %d for %s: %v", i, path, err)
		}
		frames[i] = frame{png: pngBuf.Bytes(), w: img.Bounds().Dx(), h: img.Bounds().Dy()}
	}

	// ICONDIR: reserved(2)=0, type(2)=1 (icon), count(2)=len(frames).
	_ = binary.Write(&buf, binary.LittleEndian, uint16(0))
	_ = binary.Write(&buf, binary.LittleEndian, uint16(1))
	_ = binary.Write(&buf, binary.LittleEndian, uint16(len(frames)))

	const headerSize, entrySize = 6, 16
	offset := uint32(headerSize + entrySize*len(frames))
	for _, fr := range frames {
		widthByte, heightByte := byte(fr.w), byte(fr.h)
		if fr.w >= 256 {
			widthByte = 0 // 0 means 256, per the documented .ico format
		}
		if fr.h >= 256 {
			heightByte = 0
		}
		buf.WriteByte(widthByte)
		buf.WriteByte(heightByte)
		buf.WriteByte(0) // color palette: none (true color)
		buf.WriteByte(0) // reserved
		_ = binary.Write(&buf, binary.LittleEndian, uint16(1))  // color planes
		_ = binary.Write(&buf, binary.LittleEndian, uint16(32)) // bits per pixel
		_ = binary.Write(&buf, binary.LittleEndian, uint32(len(fr.png)))
		_ = binary.Write(&buf, binary.LittleEndian, offset)
		offset += uint32(len(fr.png))
	}
	for _, fr := range frames {
		buf.Write(fr.png)
	}

	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		log.Fatalf("write %s: %v", path, err)
	}
}
